version: '3'
services:
  renewx:
    image: crosscc/ms365-e5-renew-x:latest
    volumes:
      - ./renewx/Deploy:/renewx/Deploy/
      - ./renewx/appdata:/renewx/appdata/
    ports:
      - "1066:1066"
