[www]
user = www
group = www

listen = /var/run/php-fpm83.sock

listen.owner = nginx
listen.group = nginx
listen.mode = 0660

pm = ondemand
pm.max_children = 128
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.process_idle_timeout = 60s;
pm.max_requests = 4096

pm.status_path = /fpm-status

ping.path = /ping
ping.response = pong

rlimit_files = 16384

clear_env = no

php_flag[display_errors] = off
php_admin_value[error_log] = /data/log/php83/fpm-php.www.err.log
php_admin_flag[log_errors] = on
